### ISSUE TITLE
Missing EIP list when using existing VPC

### ISSUE THREAD

**Issue by fjudith** [awslabs/harmonix#121]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

Getting the following error from the `network-constructs` when provisionning an additional provider in an existing VPC.

```sh
TypeError: this.publicEIPref is not iterable
```

## Versions

- OPA plugin versions [Required]: 0.3.4
Output from `yarn list --cwd backstage --pattern aws-apps`

## Reproduction Code [Required]

* Deploy new Environment provider in an existing VPC
* Deploy an additional Environment in the same VPC

## Expected behavior

The `network-construct` should retreive existing EIPs allocated to the public subnet of existing VPC.

## Actual behavior

The list of EIPs is not initialized or neither empty

### Terminal Output Screenshot(s)

```bash
/builds/harmonix/demo-eks-environment/.iac/opa-common-constructs/src/network-construct.ts:295
    for (const ip of this.publicEIPref) {
                          ^
TypeError: this.publicEIPref is not iterable
    at new NetworkConstruct (/builds/harmonix/demo-eks-environment/.iac/opa-common-constructs/src/network-construct.ts:295:27)
    at new OPAEKSEnvStack (/builds/harmonix/demo-eks-environment/.iac/opa-eks-environment/src/opa-eks-environment-stack.ts:85:21)
    at main (/builds/harmonix/demo-eks-environment/.iac/opa-eks-environment/src/opa-eks-env-app.ts:36:3)
    at Object.<anonymous> (/builds/harmonix/demo-eks-environment/.iac/opa-eks-environment/src/opa-eks-env-app.ts:45:1)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module.m._compile (/builds/harmonix/demo-eks-environment/.iac/opa-eks-environment/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Object.require.extensions.<computed> [as .ts] (/builds/harmonix/demo-eks-environment/.iac/opa-eks-environment/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:[120](https://gitlab.com/harmonix/demo-eks-environment/-/jobs/8173237858#L120)3:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
Subprocess exited with error 1
```

**Comment by z-sourcecode** [comment]
@fjudith thank you for your contribution!  PR is merged.
